Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,7 +44,7 @@ on:
         
 jobs:
   build:
-    runs-on: blacksmith-32vcpu-ubuntu-2404
+    runs-on: blacksmith-4vcpu-ubuntu-2404
     
     strategy:
       matrix:
@@ -77,23 +77,23 @@ jobs:
           
       - name: Configure Git
         run: |
-         git config --global user.name "jianqing"
-         git config --global user.email "2106456897@qq.com"
+          git config --global user.name "jianqing"
+          git config --global user.email "2106456897@qq.com"
 
       - name: Install repo tool
         run: |
-         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
-         chmod a+x ~/repo
-         sudo mv ~/repo /usr/local/bin/repo
+          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
+          chmod a+x ~/repo
+          sudo mv ~/repo /usr/local/bin/repo
 
       - name: Initialize repo and sync
         if: steps.cache-repo.outputs.cache-hit != 'true'
         run: |
-         mkdir -p kernel_workspace && cd kernel_workspace
-         repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ inputs.CPU }} -m ${{ matrix.FEIL }}.xml --depth=1
-         repo --trace sync -c -j$(nproc --all) --no-tags
-         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
-         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
+          mkdir -p kernel_workspace && cd kernel_workspace
+          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ inputs.CPU }} -m ${{ matrix.FEIL }}.xml --depth=1
+          repo --trace sync -c -j$(nproc --all) --no-tags
+          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
+          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
          
       - name: SukiSU-Ultra & SukiSU version
         if: ${{ inputs.kernelsu_variant == 'SukiSU-Ultra' || inputs.kernelsu_variant == 'SukiSU' }}
@@ -126,52 +126,52 @@ jobs:
           
       - name: Set up SUSFS & apply patches
         run: |
-         set -e
+          set -e
 
-         cd kernel_workspace
-         git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}
-         git clone --depth=1 https://github.com/SukiSU-Ultra/SukiSU_patch.git
-         git clone --depth=1 https://github.com/egcd123/boot.git
-         cd kernel_platform
-         cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch ./common/ || true
-         mkdir -p ./common/fs ./common/include/linux ./common/lib ./common/crypto
-         cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/ || true
-         cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/ || true
-         cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux || true
-         cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib || true
-         cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto || true
-         cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/ || true
-         cp ../boot/1.patch ./common/
-         cd ./common
-         PATCH_FILE=50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch
-         if [[ -f "$PATCH_FILE" ]]; then
-         sed -i 's/-32,12 +32,38/-32,11 +32,37/g' "$PATCH_FILE"
-         sed -i '/#include <trace\/hooks\/fs.h>/d' "$PATCH_FILE"
-         patch -p1 < "$PATCH_FILE" || true
-         fi
-         cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
-         patch -p1 -F 3 < syscall_hooks.patch || true
-         patch -p1 -F 3 < 1.patch
-         echo "✅ SUSFS 和 syscall_hooks patch 应用完成"
+          cd kernel_workspace
+          git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}
+          git clone --depth=1 https://github.com/SukiSU-Ultra/SukiSU_patch.git
+          git clone --depth=1 https://github.com/egcd123/boot.git
+          cd kernel_platform
+          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch ./common/ || true
+          mkdir -p ./common/fs ./common/include/linux ./common/lib ./common/crypto
+          cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/ || true
+          cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/ || true
+          cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux || true
+          cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib || true
+          cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto || true
+          cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/ || true
+          cp ../boot/1.patch ./common/
+          cd ./common
+          PATCH_FILE=50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch
+          if [[ -f "$PATCH_FILE" ]]; then
+          sed -i 's/-32,12 +32,38/-32,11 +32,37/g' "$PATCH_FILE"
+          sed -i '/#include <trace\/hooks\/fs.h>/d' "$PATCH_FILE"
+          patch -p1 < "$PATCH_FILE" || true
+          fi
+          cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
+          patch -p1 -F 3 < syscall_hooks.patch || true
+          patch -p1 -F 3 < 1.patch
+          echo "✅ SUSFS 和 syscall_hooks patch 应用完成"
 
       - name: Apply lz4kd Patches
         run: |
-         set -e
-         cd kernel_workspace/kernel_platform/common
-         PATCH_FILE=../../SukiSU_patch/other/zram/zram_patch/${{ inputs.KERNEL_VERSION }}/lz4kd.patch
-         if [[ -f "$PATCH_FILE" ]]; then
-         cp "$PATCH_FILE" ./lz4kd.patch
-         patch -p1 -F 3 < lz4kd.patch || true
-         else
-         echo "❗ lz4kd patch not found for kernel version ${{ inputs.KERNEL_VERSION }}"
-         fi
+          set -e
+          cd kernel_workspace/kernel_platform/common
+          PATCH_FILE=../../SukiSU_patch/other/zram/zram_patch/${{ inputs.KERNEL_VERSION }}/lz4kd.patch
+          if [[ -f "$PATCH_FILE" ]]; then
+          cp "$PATCH_FILE" ./lz4kd.patch
+          patch -p1 -F 3 < lz4kd.patch || true
+          else
+          echo "❗ lz4kd patch not found for kernel version ${{ inputs.KERNEL_VERSION }}"
+          fi
 
       - name: Set CONFIG_LOCALVERSION
         if: ${{ inputs.local_version != '-4k' }}
         run: |
-         cd kernel_workspace/kernel_platform
-         echo "Using local_version: ${{ inputs.local_version }}"
-         sed -i "s/CONFIG_LOCALVERSION=\"-4k\"/CONFIG_LOCALVERSION=\"${{ inputs.local_version }}\"/" ./common/arch/arm64/configs/gki_defconfig
+          cd kernel_workspace/kernel_platform
+          echo "Using local_version: ${{ inputs.local_version }}"
+          sed -i "s/CONFIG_LOCALVERSION=\"-4k\"/CONFIG_LOCALVERSION=\"${{ inputs.local_version }}\"/" ./common/arch/arm64/configs/gki_defconfig
 
       - name: Add SUSFS Configuration Settings
         run: |
@@ -230,40 +230,43 @@ jobs:
 
       - name: Add sched_ext
         run: |
-         cd kernel_workspace/kernel_platform/
-         git clone https://github.com/egcd123/sched_ext.git
-         cp -r ./sched_ext/* ./common/kernel/sched
-         rm -rf ./sched_ext/.git
-         cd common/kernel/sched
-         sed -i.bak '/# include "ext.c"/a\# include "hmbird_sched_proc_main.c"\n#endif\n\n#ifdef CONFIG_SLIM_SCHED\n# include "slim_sysctl.c"' build_policy.c
+          cd kernel_workspace/kernel_platform/
+          git clone https://github.com/egcd123/sched_ext.git
+          cp -r ./sched_ext/* ./common/kernel/sched
+          rm -rf ./sched_ext/.git
+          cd common/kernel/sched
+          sed -i.bak '/# include "ext.c"/a\# include "hmbird_sched_proc_main.c"\n#endif\n\n#ifdef CONFIG_SLIM_SCHED\n# include "slim_sysctl.c"' build_policy.c
 
       - name: Set build timestamp
         run: |         
-         export SOURCE_DATE_EPOCH=$(date -d "2024-12-17 23:36:49 UTC" +%s)
-         echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
+          export SOURCE_DATE_EPOCH=$(date -d "2024-12-17 23:36:49 UTC" +%s)
+          echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
          
       - name: Build kernel
         run: |
-         cd kernel_workspace/kernel_platform
-         tools/bazel run --config=fast --config=stamp --lto=thin --copt=-O${{ matrix.optimizer_level }} --jobs=$(nproc) --compilation_mode=opt --strip=always --linkopt=-fuse-ld=lld //common:kernel_aarch64_dist -- --dist_dir=dist
+          cd kernel_workspace/kernel_platform
+          CC=clang CXX=clang++ tools/bazel run --config=fast --config=stamp --lto=thin \
+            --copt=-O${{ matrix.optimizer_level }} --cxxopt="-stdlib=libc++" \
+            --linkopt="-stdlib=libc++" --jobs=$(nproc) --compilation_mode=opt \
+            --strip=always --linkopt=-fuse-ld=lld //common:kernel_aarch64_dist -- --dist_dir=dist
 
       - name: Generate Kernel lmages
         run: |
-         cd kernel_workspace/kernel_platform/dist
-         cp Image Image_original
-         curl -LO https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
-         chmod +x patch_linux
-         ./patch_linux
-         rm -f Image
-         mv oImage Image
+          cd kernel_workspace/kernel_platform/dist
+          cp Image Image_original
+          curl -LO https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
+          chmod +x patch_linux
+          ./patch_linux
+          rm -f Image
+          mv oImage Image
          
       - name: Prepare AnyKernel3 Packages
         run: |
-         cd kernel_workspace/kernel_platform/dist
-         git clone https://github.com/egcd123/AnyKernel3.git AnyKernel3-kpm --depth=1
-         rm -rf AnyKernel3-kpm/.git
-         rm -f AnyKernel3-kpm/push.sh
-         cp Image AnyKernel3-kpm/
+          cd kernel_workspace/kernel_platform/dist
+          git clone https://github.com/egcd123/AnyKernel3.git AnyKernel3-kpm --depth=1
+          rm -rf AnyKernel3-kpm/.git
+          rm -f AnyKernel3-kpm/push.sh
+          cp Image AnyKernel3-kpm/
 
       - name: Zip
         run: |
